version: "3.7"

services:

  # mysql 5.7
  urlearn_mysql:
    container_name: urlearn_mysql
    image: mysql:8.0
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlearn_db
      MYSQL_USER: develover
      MYSQL_PASSWORD: develover
    ports: 
      - "3376:3306"

  # phpmyadmin
  urlearn_phpmyadmin:
    container_name: urlearn_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
       - urlearn_mysql
    restart: 'always'
    ports: 
      - '8080:80'
    environment: 
      PMA_HOST: urlearn_mysql

  #svelte
  # urlearn_svelte:
  #   image: svelte-template:dev
  #   container_name: urlearn_svelte
  #   build: 
  #     context: ../
  #     dockerfile: ./docker/docker/svelte/Dockerfile
  #   ports:
  #     - "5000:5000"
  #     - "35729:35729"
  